### ISSUE TITLE
【加入申请】Jodesen

### ISSUE THREAD

**Issue by Jodesen** [CNHOMO/About#2]
### 名字/ID

鸭鸭

### 邮箱/Email

jodesen_yang@163.com

### 想要学习的是？

不着急，我主攻前端方向，进HOMO大家庭玩玩

**Comment by MoonCC233** [comment]
已发送邀请，访问 https://github.com/orgs/CNHOMO/invitation 同意即可！

**Comment by MoonCC233** [comment]
Add Jodesen successfully!
